### ISSUE TITLE
integrated with the @vue/apollo-composable while building have the "define is not defined" error

### ISSUE THREAD

**Issue by lymanlai** [antfu/vitesse#133]
**Describe the bug/issue**
1. add the @vue/apollo-composable: https://v4.apollo.vuejs.org/guide-composable/setup.html
2. pnpm run build
cause the following error

```
ReferenceError: define is not defined
    at Object.<anonymous> (app/node_modules/.pnpm/registry.nlark.com/@vue/apollo-composable@4.0.0-alpha.12_a8f1dfa507b9f65e6b5e71908ade3ac8/node_modules/@vue/apollo-composable/dist/vue-apollo-composable.js:48:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (/Users/lyman/Desktop/opsk/web-app/.vite-ssg-temp/main.js:35:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
 ERROR  Command failed with exit code 1.

```

I think it's the problem that while the vite-ssg try to use the `/@vue/apollo-composable/dist/vue-apollo-composable.js` file that it include the `define` symbol

**Comment by antfu** [comment]
Close as I don't think it's really related to this template - please open issue in the right repo.
