### ISSUE TITLE
SSG Builds broken - Need quick help configuring builds

### ISSUE THREAD

**Issue by jiazengp** [antfu/vitesse#173]
I added `createWebHistory(import.meta.env.BASE_URL)` to configure bases to deploy to github pages.All build modes were working without issue until the addition of this new code.

## Error trace

``` md
ReferenceError: window is not defined
    at useHistoryStateNavigation (F:\vitesse-main\node_modules\.pnpm\vue-router@4.0.11_vue@3.2.4\node_modules\vue-router\dist\vue-router.cjs.js:505:35)
    at Object.createWebHistory (F:\vitesse-main\node_modules\.pnpm\vue-router@4.0.11_vue@3.2.4\node_modules\vue-router\dist\vue-router.cjs.js:597:31)
    at Module.<anonymous> (F:\vitesse-main\.vite-ssg-temp\main.js:938:77)
    at Module.o._compile (F:\vitesse-main\node_modules\.pnpm\jiti@1.11.0\node_modules\jiti\dist\v8cache.js:2:2778)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)       
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)    
    at require (internal/modules/cjs/helpers.js:88:18)
    at __require (F:\vitesse-main\node_modules\.pnpm\vite-ssg@0.14.5_20694550d252f8cd45c3edfcdb6eff74\node_modules\vite-ssg\dist\chunk-3FHQZVYO.js:22:12)
 ERROR  Command failed with exit code 1.
```

## Full build logs

``` md
> @ build F:\vitesse-main
> cross-env NODE_ENV=production vite-ssg build


[vite-ssg] Build for client...
vite v2.5.0 building for production...
✓ 120 modules transformed.


dist/index.html                                0.97 KiB
dist/manifest.webmanifest                      0.45 KiB
dist/ssr-manifest.json                         12.15 KiB
dist/assets/404.94208237.js                    1.02 KiB / brotli: 0.52 KiB
dist/assets/home.a7b0025d.js                   0.37 KiB / brotli: 0.24 KiB
dist/assets/about.753931a8.js                  0.73 KiB / brotli: 0.37 KiB
dist/assets/virtual_pwa-register.709e41b3.js   5.48 KiB / brotli: 2.00 KiB
dist/assets/_...all_.407543d7.js               0.22 KiB / brotli: 0.16 KiB
dist/assets/app.97438260.js                    13.97 KiB / brotli: 4.33 KiB
dist/assets/_name_.1aa93590.js                 1.76 KiB / brotli: 0.90 KiB
dist/assets/app.2eda8b07.css                   6.82 KiB / brotli: 1.91 KiB
dist/assets/vendor.68c6b446.js                 114.20 KiB / brotli: 37.91 KiB

[vite-ssg] Build for server...
vite v2.5.0 building SSR bundle for production...
✓ 45 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.45 KiB
.vite-ssg-temp/main.js                     48.91 KiB
.vite-ssg-temp/assets/style.9b035311.css   8.24 KiB
ReferenceError: window is not defined
    at useHistoryStateNavigation (F:\vitesse-main\node_modules\.pnpm\vue-router@4.0.11_vue@3.2.4\node_modules\vue-router\dist\vue-router.cjs.js:505:35)
    at Object.createWebHistory (F:\vitesse-main\node_modules\.pnpm\vue-router@4.0.11_vue@3.2.4\node_modules\vue-router\dist\vue-router.cjs.js:597:31)
    at Module.<anonymous> (F:\vitesse-main\.vite-ssg-temp\main.js:938:77)
    at Module.o._compile (F:\vitesse-main\node_modules\.pnpm\jiti@1.11.0\node_modules\jiti\dist\v8cache.js:2:2778)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)       
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)    
    at require (internal/modules/cjs/helpers.js:88:18)
    at __require (F:\vitesse-main\node_modules\.pnpm\vite-ssg@0.14.5_20694550d252f8cd45c3edfcdb6eff74\node_modules\vite-ssg\dist\chunk-3FHQZVYO.js:22:12)
 ERROR  Command failed with exit code 1.
```

## Code
`src/main.ts`

``` ts
// register vue composition api globally
import 'vue-global-api'
import { ViteSSG } from 'vite-ssg'
import { setupLayouts } from 'virtual:generated-layouts'
import { createWebHistory } from 'vue-router'
import generatedRoutes from 'virtual:generated-pages'
import App from './App.vue'

// windicss layers
import 'virtual:windi-base.css'
import 'virtual:windi-components.css'
// your custom styles here
import './styles/index.scss'
// windicss utilities should be the last style import
import 'virtual:windi-utilities.css'
// windicss devtools support (dev only)
import 'virtual:windi-devtools'

const routes = setupLayouts(generatedRoutes)

// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(
  App,
  { routes, history: createWebHistory(import.meta.env.BASE_URL) },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map((i) =>
      i.install?.(ctx)
    )
  }
)
```

**Comment by antfu** [comment]
`createWebHistory` is not SSR compatible. Provide `base` instead https://github.com/antfu/vite-ssg/blob/afe8570c40f6161d12a912d9454926ec438223c8/src/types.ts#L94
