### ISSUE TITLE
"Error: [auto-import] failed to load @vueuse/core, have you installed it?"

### ISSUE THREAD

**Issue by shamscorner** [antfu/vitesse#178]
When I run `pnpm dev`, I am getting this error log on my local. Everything seems Ok but still, I am getting this. Am I missing something? - not sure why! By the way, I have run the `pnpm i` command.

```
failed to load config from /home/shamscorner/Projects/local/vitesse-app-demo/vite.config.ts
error when starting dev server:
Error: [auto-import] failed to load @vueuse/core, have you installed it?
    at vueuse_core_default (/home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin-auto-import@0.1.5_vite@2.5.1/node_modules/unplugin-auto-import/dist/chunk-U6Z5VRX4.js:136:13)
    at /home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin-auto-import@0.1.5_vite@2.5.1/node_modules/unplugin-auto-import/dist/chunk-4DE7XTP3.js:32:51
    at Array.forEach (<anonymous>)
    at flattenImportsMap (/home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin-auto-import@0.1.5_vite@2.5.1/node_modules/unplugin-auto-import/dist/chunk-4DE7XTP3.js:27:36)
    at resolveOptions (/home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin-auto-import@0.1.5_vite@2.5.1/node_modules/unplugin-auto-import/dist/chunk-4DE7XTP3.js:16:19)
    at /home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin-auto-import@0.1.5_vite@2.5.1/node_modules/unplugin-auto-import/dist/chunk-4DE7XTP3.js:108:20
    at /home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/unplugin@0.0.8_vite@2.5.1/node_modules/unplugin/dist/index.cjs:44:23
    at Object.<anonymous> (/home/shamscorner/Projects/local/vitesse-app-demo/vite.config.ts:58:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.require.extensions.<computed> [as .ts] (/home/shamscorner/Projects/local/vitesse-app-demo/node_modules/.pnpm/vite@2.5.1/node_modules/vite/dist/node/chunks/dep-972722fa.js:75935:20)
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
Do you have this file? https://github.com/antfu/vitesse/blob/main/.npmrc

**Comment by shamscorner** [comment]
@antfu I was trying with an older version of node `12.**`. I have updated my node version `14.**`. Now it is working. Thanks for the reply. I am closing this issue.

**Comment by flahol** [comment]
I have the same error on ubuntu 21.04, nodejs 16.8.0 and i do have the file .npmrc

```
failed to load config from /home/patrice/Websites/obizoo/obizoo.vue/vite.config.ts
error when starting dev server:
Error: [auto-import] failed to load @vueuse/core, have you installed it?
    at vueuse_core_default (/home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin-auto-import@0.3.3_@vueuse+core@6.0.0+vite@2.5.3/node_modules/unplugin-auto-import/dist/chunk-T5OU4655.js:227:13)
    at /home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin-auto-import@0.3.3_@vueuse+core@6.0.0+vite@2.5.3/node_modules/unplugin-auto-import/dist/chunk-5I5CMYBW.js:39:51
    at Array.forEach (<anonymous>)
    at flattenImportsMap (/home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin-auto-import@0.3.3_@vueuse+core@6.0.0+vite@2.5.3/node_modules/unplugin-auto-import/dist/chunk-5I5CMYBW.js:34:36)
    at resolveOptions (/home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin-auto-import@0.3.3_@vueuse+core@6.0.0+vite@2.5.3/node_modules/unplugin-auto-import/dist/chunk-5I5CMYBW.js:18:19)
    at /home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin-auto-import@0.3.3_@vueuse+core@6.0.0+vite@2.5.3/node_modules/unplugin-auto-import/dist/chunk-5I5CMYBW.js:159:20
    at /home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/unplugin@0.2.7_vite@2.5.3/node_modules/unplugin/dist/index.js:79:23
    at Object.<anonymous> (/home/patrice/Websites/obizoo/obizoo.vue/vite.config.ts:59:30)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.require.extensions.<computed> [as .ts] (/home/patrice/Websites/obizoo/obizoo.vue/node_modules/.pnpm/vite@2.5.3/node_modules/vite/dist/node/chunks/dep-1be34a63.js:77161:20)
 ERROR  Command failed with exit code 1.
```
