### ISSUE TITLE
Different behaviour on CI builds

### ISSUE THREAD

**Issue by campino2k** [antfu/vitesse#218]
Output when starting build manually
```
[vite-ssg] Rendering Pages... (2)
[vite-ssg] Critical CSS generation enabled via `critters`
dist/team.html        9.00 KiB
dist/index.html       8.21 KiB
```

Output when same code on same machine, using same user, but called via gitlab runner (I have a gitlab-runner on this machine to handle gitlab pages builds):
```
[vite-ssg] Rendering Pages... (2)
[vite-ssg] Critical CSS generation enabled via `critters`
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/<builddir>/node_modules/.pnpm/@vue+runtime-core@3.2.20/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2150:15)
    at createComponentInstance (/<builddir>/node_modules/.pnpm/@vue+runtime-core@3.2.20/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:4983:23)
    at renderComponentVNode (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:194:22)
    at Object.ssrRenderComponent (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:620:12)
    at _sfc_ssrRender$2 (/<builddir>/.vite-ssg-temp/main.js:253:24)
    at renderComponentSubTree (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:260:13)
    at renderComponentVNode (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:211:16)
    at renderVNode (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:301:22)
    at renderComponentSubTree (/<builddir>/node_modules/.pnpm/@vue+server-renderer@3.2.20_vue@3.2.20/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:266:13)
```

Sometimes the build succeedes, but the app will exit with console error "useHead is undefined"

**Comment by antfu** [comment]
Make sure you use the same Node version and >=v14

**Comment by yxonic** [comment]
This may be related to https://github.com/antfu/unplugin-vue-components/issues/203

For a workaround, provide `exclude` option for the component plugin in `vite.config.ts`:

```ts
export default defineConfig({
  ...
  plugins: [
    Components({
      ...
      exclude: [/\/node_modules\//, /\/.git\//], // <- this
    }),
  ],
})
```

**Comment by campino2k** [comment]
This may be able to solve another thing I posted in Discussions. I'll try this out later. Thanks!
