### ISSUE TITLE
"pnpm dev" fails after creating a repo from this template

### ISSUE THREAD

**Issue by tenzint** [antfu/vitesse#256]
**Recreation of Bug**
I simply created a repo from this `antfu/vitesse` template. Installed the `pnpm` package as I usually use the default `npm`; ran `pnpm install`; then ran `pnpm dev`. This results in some error [ERR_INVALID_ARG_TYPE] that I have pasted below.

**Package versions**
Node = v12.18.3
Pnpm = 6.24.1
Npm = 8.3.0

**Error message paste**
```js
$ pnpm dev

> @ dev C:\Users\16477\Documents\vitesse-todo
> vite --port 3333 --open

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:454:10)
    at readFileSync (fs.js:364:35)
    at vueuse_core_default (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-T37YOLOK.js:284:55)
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:42:51
    at Array.forEach (<anonymous>)
    at flattenImportsMap (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:37:36)
    at resolveOptions (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:18:19)
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:218:20
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin@0.2.21_vite@2.7.2\node_modules\unplugin\dist\index.js:82:23
    at Object.<anonymous> (C:\Users\16477\Documents\vitesse-todo\vite.config.ts:60:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
failed to load config from C:\Users\16477\Documents\vitesse-todo\vite.config.ts
error when starting dev server:
Error: [auto-import] failed to load @vueuse/core, have you installed it?
    at vueuse_core_default (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-T37YOLOK.js:290:13)
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:42:51
    at Array.forEach (<anonymous>)
    at flattenImportsMap (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:37:36)
    at resolveOptions (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:18:19)
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin-auto-import@0.5.3_@vueuse+core@7.3.0+vite@2.7.2\node_modules\unplugin-auto-import\dist\chunk-5WJMMGHH.js:218:20
    at C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\unplugin@0.2.21_vite@2.7.2\node_modules\unplugin\dist\index.js:82:23
    at Object.<anonymous> (C:\Users\16477\Documents\vitesse-todo\vite.config.ts:60:30)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\16477\Documents\vitesse-todo\node_modules\.pnpm\vite@2.7.2\node_modules\vite\dist\node\chunks\dep-7817f5b4.js:82463:20)
 ELIFECYCLE  Command failed with exit code 1.
```

It seems to be that I am having an incompatible version for some package(s), but I don't know what. I appreciate any help. Thanks in advance

**Comment by Flint-company** [comment]
Hi @tenzint , 
This may be caused by an old version of node.
I had the same issue and made it work by updating Node to latest v17.3.0 and run again pnpm dev.
Hope it helps resolve your issue.
If this is the case it could be mentioned in the Readme.

**Comment by tenzint** [comment]
Hi Flint-company, yes sir. I heeded your advice and downloaded the stable version v16.x.x. Wow, version 12.8.3 is outdated, time sure flies. Thank you and hope you have a great day.
