### ISSUE TITLE
Vite internal server error on YML files on setup

### ISSUE THREAD

**Issue by NathanVG** [antfu/vitesse#270]
Hi, 

I followed the steps described in the readme to setup this template. 
After having run the install and running `pnpm dev` for the first time, an error is immediately thrown: 

```
 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .yml file format.
  Plugin: vite:import-analysis
  File: /Users/Path/To/Project/locales/fr.yml
  7  |    toggle_langs: Changer de langue
  8  |  intro:
  9  |    desc: Exemple d'application Vite
     |                                    ^
  10 |    dynamic-route: Démo de route dynamique
  11 |    hi: Salut, {name}!
      at formatError (/Users/Path/To/Project/node_modules/.pnpm/vite@2.7.6/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42631:46)
      at TransformContext.error (/Users/Path/To/Project/node_modules/.pnpm/vite@2.7.6/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42627:19)
      at TransformContext.transform (/Users/Path/To/Project/node_modules/.pnpm/vite@2.7.6/node_modules/vite/dist/node/chunks/dep-fcec4469.js:81321:22)
      at async Object.transform (/Users/Path/To/Project/node_modules/.pnpm/vite@2.7.6/node_modules/vite/dist/node/chunks/dep-fcec4469.js:42847:30)
      at async doTransform (/Users/Path/To/Project/node_modules/.pnpm/vite@2.7.6/node_modules/vite/dist/node/chunks/dep-fcec4469.js:57918:29)
```

Is there a package or plugin missing in the template or on my side?

**Comment by NathanVG** [comment]
Turns out I'm an idiot, and developing in a dropbox folder is a bad idea. Moved my project from my dropbox folder and everything works.
