### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by husayt** [antfu/vitesse#28]
Hi, I get this error, trying to run build. Did upgrade all the dependencies, but still error is there. Maybe someone has stumbled on something like this before?

```
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:5265:30)
    at Module.error (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:9842:16)
    at tryParse (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:9723:23)
    at Module.setSource (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:10149:19)
    at ModuleLoader.addModuleSource (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:18319:20)
    at async ModuleLoader.fetchModule (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:18375:9)
    at async Promise.all (index 0) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: Unexpected token (1:0)
      at Object.pp$4.raise (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:15573:13)
      at Object.pp.unexpected (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:13265:8)
      at Object.pp$3.parseExprAtom (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14972:10)
      at Object.pp$3.parseExprSubscripts (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14775:19)
      at Object.pp$3.parseMaybeUnary (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14752:17)
      at Object.parseMaybeUnary (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:19167:29)
      at Object.pp$3.parseExprOps (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14687:19)
      at Object.pp$3.parseMaybeConditional (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14670:19)
      at Object.pp$3.parseMaybeAssign (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14638:19)
      at Object.pp$3.parseExpression (C:\_code\JS\_tmp\vitesse\node_modules\.pnpm\rollup@2.35.0\node_modules\rollup\dist\shared\rollup.js:14604:19) {
    pos: 0,
    loc: Position { line: 1, column: 0 },
    raisedAt: 1
  },
  id: 'C:\\_code\\JS\\_tmp\\vitesse\\index.html',
  pos: 0,
  loc: {
    file: 'C:\\_code\\JS\\_tmp\\vitesse\\index.html',
    line: 1,
    column: 0
  },
  frame: '1: <!DOCTYPE html>\r\n   ^\n2: <html lang="en">\r\n3: <head>\r',
  watchFiles: [ 'C:\\_code\\JS\\_tmp\\vitesse\\index.html' ]
}
 ERROR  Command failed with exit code 1.
```

**Comment by husayt** [comment]
This is fixed with latest vitesse for vite 2.

THANK YOU
