### ISSUE TITLE
Named Export from CommonJS module fails

### ISSUE THREAD

**Issue by Valentin-Seehausen** [antfu/vitesse#296]
When using https://github.com/Maronato/vue-toastification#using-a-custom-component

like (in modules):

```
import type { PluginOptions } from 'vue-toastification'
import Toast, { POSITION } from 'vue-toastification'
import type { UserModule } from '~/types'
import 'vue-toastification/dist/index.css'

export const install: UserModule = ({ app, isClient }) => {
  if (!isClient) return
  const options: PluginOptions = {
    position: POSITION.BOTTOM_RIGHT,
    timeout: false,
  }
  app.use(Toast, options)
}
```

And build, I get:

```
[vite-ssg] Build for server...
vite v2.7.12 building SSR bundle for production...
✓ 76 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/assets/style.23fdc254.css   49.34 KiB
.vite-ssg-temp/main.mjs                    593.87 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/valentin/Development/art/seven-dots-monorepo/vitesse/.vite-ssg-temp/main.mjs:24
import Toast, { POSITION, useToast, TYPE } from "vue-toastification";
                ^^^^^^^^
SyntaxError: Named export 'POSITION' not found. The requested module 'vue-toastification' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-toastification';
const { POSITION, useToast, TYPE } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async build (/Users/valentin/Development/art/seven-dots-monorepo/vitesse/node_modules/vite-ssg/dist/node/cli.cjs:180:44)
    at async Object.handler (/Users/valentin/Development/art/seven-dots-monorepo/vitesse/node_modules/vite-ssg/dist/node/cli.cjs:294:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

any idea?

**Comment by userquin** [comment]
just apply the suggestion on the log:
```ts
import pkg from 'vue-toastification';
const { POSITION, useToast, TYPE } = pkg;
```

**Comment by Valentin-Seehausen** [comment]
Thanks @userquin 

I did this before, and still on server build get:

```
[vite-ssg] Build for server...
vite v2.7.12 building SSR bundle for production...
✓ 77 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/assets/style.9f1d3a3e.css   49.73 KiB
.vite-ssg-temp/main.mjs                    601.84 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/valentin/Development/art/seven-dots-monorepo/vitesse/.vite-ssg-temp/main.mjs:24
import Toast, { useToast as useToast$1, TYPE as TYPE$1 } from "vue-toastification";
                                        ^^^^
SyntaxError: Named export 'TYPE' not found. The requested module 'vue-toastification' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-toastification';
const { useToast: useToast$1, TYPE: TYPE$1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async build (/Users/valentin/Development/art/seven-dots-monorepo/vitesse/node_modules/vite-ssg/dist/node/cli.cjs:180:44)
    at async Object.handler (/Users/valentin/Development/art/seven-dots-monorepo/vitesse/node_modules/vite-ssg/dist/node/cli.cjs:294:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I import like 

```
import 'vue-toastification/dist/index.css'
const { POSITION, useToast, TYPE } = Toast
```

**Comment by Valentin-Seehausen** [comment]
Is this related to Toastification?

**Comment by Valentin-Seehausen** [comment]
My workaround is to only build for client (no SSG).

**Comment by userquin** [comment]
@Valentin-Seehausen @ArgekarStudios try switching to `cjs` using `format: 'cjs'` on `ssgOptions`

**Comment by ArgekarStudios** [comment]
@Valentin-Seehausen  that worked perfectly thanks a lot...
