### ISSUE TITLE
[Vue Router warn]: No match found for location with path 

### ISSUE THREAD

**Issue by tshemeng** [antfu/vitesse#32]
`vitesse` template not works on my pc, here my step:

```bash
git clone https://github.com/antfu/vitesse.git
cd vitesse
pnpm i
pnpm dev
```
I got errors in browser:

> [Vue Router warn]: No match found for location with path "/"
> [Vue Router warn]: No match found for location with path "/about"

Environment:
- Windows 10 x64
- Node.js 14.14.0

**Comment by antfu** [comment]
Can't repro on the master branch, can you share more info? Thanks.

**Comment by tshemeng** [comment]
use `npx degit antfu/vitesse my-vitesse-app` sovled.

**Comment by feryardiant** [comment]
Come across same issue with the following log

```
[vite-ssg] Rendering Pages... (13)
[Vue Router warn]: No match found for location with path "/"
[Vue Router warn]: No match found for location with path "/"
[Vue Router warn]: No match found for location with path "/"
[Vue Router warn]: No match found for location with path "/"
TypeError: Cannot create property '__props' on string 'post'
    at normalizePropsOptions (my-project\node_modules\.pnpm\@vue\runtime-core@3.0.7\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:1363:30)
    at createComponentInstance (my-project\node_modules\.pnpm\@vue\runtime-core@3.0.7\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5233:23)
    at renderComponentVNode (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:156:22)
    at Object.ssrRenderComponent (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:469:12)
    at my-project\.vite-ssg-temp\main.js:1204:28
    at renderComponentSubTree (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:208:13)
    at renderComponentVNode (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:174:16)
    at renderVNode (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:245:22)
    at renderComponentSubTree (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:214:13)
    at renderComponentVNode (my-project\node_modules\.pnpm\@vue\server-renderer@3.0.7_vue@3.0.7\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:174:16)
 ERROR  Command failed with exit code 1.
```
Then I realized that I don't have any _index_ in my `pages` directory.
