### ISSUE TITLE
Unable to build when part of a pnpm monorepo/workspace

### ISSUE THREAD

**Issue by waltoncon** [antfu/vitesse#322]
After a fresh clone into a pnpm workspace, there is an error during build.

This is the complete output of `pnpm run build`
<details>
  <summary>Output</summary>  

  ```

> @ build /home/waltonc/code/vitesse-pnpm-workspace/app
> vite-ssg build


[vite-ssg] Build for client...
vite v2.9.1 building for production...
✓ 47 modules transformed.
[vite-plugin-pwa] [vite]: Rollup failed to resolve import "workbox-window" from "../../../../../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite@2.9.1/node_modules/vite/dist/node/chunks/dep-611778e0.js:39103
            throw new Error(`[vite]: Rollup failed to resolve import "${id}" from "${importer}".\n` +
                  ^

Error: [vite]: Rollup failed to resolve import "workbox-window" from "../../../../../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite@2.9.1/node_modules/vite/dist/node/chunks/dep-611778e0.js:39103:19)
    at onwarn (/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite@2.9.1/node_modules/vite/dist/node/chunks/dep-611778e0.js:38919:13)
    at Object.onwarn (/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/shared/rollup.js:23129:13)
    at ModuleLoader.handleResolveId (/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/shared/rollup.js:22419:26)
    at /home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/rollup@2.70.1/node_modules/rollup/dist/shared/rollup.js:22380:26 {
  watchFiles: [
    '/home/waltonc/code/vitesse-pnpm-workspace/app/index.html',
    'vite/modulepreload-polyfill',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/main.ts',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite-ssg@0.19.0_6a44acb5bf8b42d72d0c4bc9f4e36c5f/node_modules/vite-ssg/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@unocss+reset@0.30.8/node_modules/@unocss/reset/package.json',
    '/@vite-plugin-pages/generated-pages',
    '/@vite-plugin-vue-layouts/generated-layouts',
    '/__uno.css',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/modules/i18n.ts',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/modules/nprogress.ts',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/modules/pinia.ts',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/modules/pwa.ts',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite-ssg@0.19.0_6a44acb5bf8b42d72d0c4bc9f4e36c5f/node_modules/vite-ssg/dist/index.mjs',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/App.vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@unocss+reset@0.30.8/node_modules/@unocss/reset/tailwind.css',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/styles/main.css',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite@2.9.1/node_modules/vite/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/pages/index.vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/pages/README.md',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/pages/[...all].vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/pages/about.md',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/pages/hi/[name].vue',
    'vite/preload-helper',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/layouts/default.vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/layouts/404.vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/layouts/home.vue',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue@3.2.31/node_modules/vue/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-router@4.0.14_vue@3.2.31/node_modules/vue-router/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vueuse+head@0.7.5_vue@3.2.31/node_modules/@vueuse/head/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue@3.2.31/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-router@4.0.14_vue@3.2.31/node_modules/vue-router/dist/vue-router.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vueuse+head@0.7.5_vue@3.2.31/node_modules/@vueuse/head/dist/index.mjs',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite-ssg@0.19.0_6a44acb5bf8b42d72d0c4bc9f4e36c5f/node_modules/vite-ssg/dist/chunks/state.mjs',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vite-ssg@0.19.0_6a44acb5bf8b42d72d0c4bc9f4e36c5f/node_modules/vite-ssg/dist/chunks/ClientOnly.mjs',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-i18n@9.1.9_vue@3.2.31/node_modules/vue-i18n/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/pinia@2.0.13_typescript@4.6.3+vue@3.2.31/node_modules/pinia/package.json',
    '/@vite-plugin-pages/route-block',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress/nprogress.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/pinia@2.0.13_typescript@4.6.3+vue@3.2.31/node_modules/pinia/dist/pinia.esm-browser.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/de.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/en.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/es.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/fr.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/id.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/it.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/ja.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/ko.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/pl.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/pt-BR.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/ru.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/tr.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/vi.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/locales/zh-CN.yml',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-i18n@9.1.9_vue@3.2.31/node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/stores/user.ts',
    '/@vite-plugin-pwa/virtual:pwa-register',
    '/home/waltonc/code/vitesse-pnpm-workspace/app/src/components/Footer.vue',
    'plugin-vue:export-helper',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vue+runtime-dom@3.2.31/node_modules/@vue/runtime-dom/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vue+runtime-dom@3.2.31/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vue+devtools-api@6.1.4/node_modules/@vue/devtools-api/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@vue+devtools-api@6.1.4/node_modules/@vue/devtools-api/lib/esm/index.js',
    '\x00commonjsHelpers.js',
    '\x00/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress/nprogress.js?commonjs-module',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-demi@0.12.5_vue@3.2.31/node_modules/vue-demi/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/vue-demi@0.12.5_vue@3.2.31/node_modules/vue-demi/lib/index.mjs',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+shared@9.1.9/node_modules/@intlify/shared/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+core-base@9.1.9/node_modules/@intlify/core-base/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+vue-devtools@9.1.9/node_modules/@intlify/vue-devtools/package.json',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+shared@9.1.9/node_modules/@intlify/shared/dist/shared.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+core-base@9.1.9/node_modules/@intlify/core-base/dist/core-base.esm-bundler.js',
    '/home/waltonc/code/vitesse-pnpm-workspace/node_modules/.pnpm/@intlify+vue-devtools@9.1.9/node_modules/@intlify/vue-devtools/dist/vue-devtools.esm-bundler.js'
  ],
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-pwa',
  hook: 'buildEnd'
}
 ELIFECYCLE  Command failed with exit code 1.
  ```

</details>

## Reproduction step

```shell
mkdir vitesse-pnpm-workspace
cd vitesse-pnpm-workspace
pnpm init -y
printf "packages:\n  - 'app'" > pnpm-workspace.yaml
gh repo clone antfu/vitesse app
pnpm install
cd app
pnpm run build
```

**Comment by userquin** [comment]
Try adding workbox-window as dev dependency on vitesse

**Comment by waltoncon** [comment]
Looks like it was down to the placement of `.npmrc`. When trying to install workbox-window pnpm exited with an  `ERR_PNPM_PUBLIC_HOIST_PATTERN_DIFF` error. 

After deleting both `node_modules` folders, moving `.npmrc` from `vitesse-pnpm-workspace/app/` to `vitesse-pnpm-workspace/`, and reinstalling from `vitesse-pnpm-workspace/`, build started working.
