### ISSUE TITLE
Internal server error: /__uno.css:34:28: Unknown word

### ISSUE THREAD

**Issue by Youdaman** [antfu/vitesse#330]
Followed the "Clone to local" instructions https://github.com/antfu/vitesse#clone-to-local

Not sure if related to https://github.com/unocss/unocss/issues/696 or https://github.com/unocss/unocss/issues/146

`pnpm dev` resulted in the following error:

```
[plugin:vite:css] [/__uno.css:34:28](): Unknown word
/__uno.css:34:28
    at Input.error ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\input.js:148:16]())
    at Parser.unknownWord ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\parser.js:540:22]())
    at Parser.other ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\parser.js:164:12]())
    at Parser.parse ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\parser.js:72:16]())
    at parse ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\parse.js:11:12]())
    at new LazyResult ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\lazy-result.js:133:16]())
    at Processor.process ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\postcss@8.4.12\node_modules\postcss\lib\processor.js:28:14]())
    at compileCSS ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:27850:10]())
    at async TransformContext.transform ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\vite@2.9.1\node_modules\vite\dist\node\chunks\dep-611778e0.js:27417:55]())
    at async TransformContext.plugin.transform ([C:\Users\Youdaman\Desktop\my-vitesse-app\node_modules\.pnpm\vite-plugin-inspect@0.4.3_vite@2.9.1\node_modules\vite-plugin-inspect\dist\index.cjs:40:25]()
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```
![localhost_3333_](https://user-images.githubusercontent.com/287330/162629530-f1e28f2b-6121-4649-854c-09c12f90fefe.png)

**Comment by antfu** [comment]
Forgot to remove the test code 😅 Should be fixed now
