### ISSUE TITLE
Build fails due to VitePWA

### ISSUE THREAD

**Issue by zigomir** [antfu/vitesse#34]
Hi! Awesome template, thanks for sharing!

I jut tried vitesse locally and while `pnpm dev` works just fine, `pnpm build` fails for me like so:

```
❯ pnpm build

> @ build /Users/ziga/development/ziga_vitesse
> cross-env NODE_ENV=production vite-ssg build --script async

[vite-ssg] Build for client...
building for production...
/Users/ziga/development/ziga_vitesse/node_modules/.pnpm/workbox-build@6.0.2/node_modules/workbox-build/build/lib/populate-sw-template.js:41
    throw new Error(errors['no-manifest-entries-or-runtime-caching']);
          ^

Error: Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob options are set to match one or more files, and/or configure the runtimeCaching option.
    at module.exports (/Users/ziga/development/ziga_vitesse/node_modules/.pnpm/workbox-build@6.0.2/node_modules/workbox-build/build/lib/populate-sw-template.js:41:11)
    at module.exports (/Users/ziga/development/ziga_vitesse/node_modules/.pnpm/workbox-build@6.0.2/node_modules/workbox-build/build/lib/write-sw-using-default-template.js:50:25)
    at async generateSW (/Users/ziga/development/ziga_vitesse/node_modules/.pnpm/workbox-build@6.0.2/node_modules/workbox-build/build/generate-sw.js:229:21)
 ERROR  Command failed with exit code 1.
```

I figured workbox is used by `VitePWA` and when I comment out `VitePWA` from `vite.config.ts` build succeeds.

**Comment by antfu** [comment]
Can't repro on the master branch. Can you share more info? Thanks.

**Comment by zigomir** [comment]
Reproduction steps for me are:

```sh
npx degit antfu/vitesse my-vitesse-app
cd my-vitesse-app
pnpm i
pnpm build
```

Versions used

```
macOS 11.1
node --version
v15.5.1
pnpm --version
5.14.3
```

**Comment by SamuelAlev** [comment]
Got the same error, except it works on macOS and fails on Github Actions.

**Comment by antfu** [comment]
Confirmed on Netlify build as well (not on my mac for some reasons). Probably a bug from the workbox upstream. Will have a look later.
