### ISSUE TITLE
Error filename with new version of markdown-it-shiki 0.6

### ISSUE THREAD

**Issue by flahol** [antfu/vitesse#442]
### Describe the bug

After updating to version 0.6 of markdown-it-shiki, an error occured when starting dev.
```
failed to load config from /home/patrice/Websites/obizoo/www.2.obizoo.com/vite.config.ts
error when starting dev server:
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:377:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at Function.MarkdownItShiki (/home/patrice/Websites/obizoo/www.2.obizoo.com/node_modules/.pnpm/markdown-it-shiki@0.6.0/node_modules/markdown-it-shiki/dist/index.js:69:54)
    at MarkdownIt.use (/home/patrice/Websites/obizoo/www.2.obizoo.com/node_modules/.pnpm/markdown-it@13.0.1/node_modules/markdown-it/lib/index.js:497:10)
    at Object.markdownItSetup (/home/patrice/Websites/obizoo/www.2.obizoo.com/vite.config.ts:100:12)
    at createMarkdown (/home/patrice/Websites/obizoo/www.2.obizoo.com/node_modules/.pnpm/vite-plugin-vue-markdown@0.22.1_vite@3.2.0/node_modules/vite-plugin-vue-markdown/dist/index.js:85:11)
    at VitePluginMarkdown (/home/patrice/Websites/obizoo/www.2.obizoo.com/node_modules/.pnpm/vite-plugin-vue-markdown@0.22.1_vite@3.2.0/node_modules/vite-plugin-vue-markdown/dist/index.js:272:25)
    at Object.<anonymous> (/home/patrice/Websites/obizoo/www.2.obizoo.com/vite.config.ts:96:49)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at _require.extensions.<computed> [as .js] (file:///home/patrice/Websites/obizoo/www.2.obizoo.com/node_modules/.pnpm/vite@3.2.0/node_modules/vite/dist/node/chunks/dep-61d2428a.js:65746:24)
 ELIFECYCLE  Command failed with exit code 1.
```
After downgraded to version ^0.5.0, no error

### Reproduction

no

### System Info

```Shell
ubuntu 22.10, ...
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Codermar** [comment]
I have the same issue. Any version after 0.5.1 in my case

**Comment by YunYouJun** [comment]
Vitesse use `@shikijs/markdown-it` now.

https://github.com/antfu-collective/vitesse/blob/8a01bc9283fedcd63e750af55a75496361789a81/package.json#L33
