### ISSUE TITLE
An error occurred while building

### ISSUE THREAD

**Issue by chengpeiquan** [antfu/vitesse#48]
Hi, Anthony, I use this template to create a demo, there are two problems that make it impossible to use directly.

key|value
:--|:--
repo|https://github.com/chengpeiquan/vitesse-demo
node -v|v14.4.0
system|Windows 10

## The First Error

At the beginning, I install all package and run dev, an error occurred in the program, the log is as follows:

```
E:\Project\test\demo\vitesse-demo (main -> origin)
λ yarn dev
yarn run v1.22.10
$ vite
Optimizable dependencies detected:
@vueuse/core, @vueuse/head, nprogress, prism-theme-vars, vue, vue-i18n, vue-router
Pre-bundling them to speed up dev server page load...
(this will be run only when your dependencies or config have changed)
(node:15100) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '\Project\test\demo\vitesse-demo\node_modules\.vite\esbuild.json'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at optimizeDeps (E:\Project\test\demo\vitesse-demo\node_modules\vite\dist\node\chunks\dep-b48a59d1.js:71274:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOptimize (E:\Project\test\demo\vitesse-demo\node_modules\vite\dist\node\chunks\dep-b48a59d1.js:71717:13)
    at async Server.httpServer.listen (E:\Project\test\demo\vitesse-demo\node_modules\vite\dist\node\chunks\dep-b48a59d1.js:71730:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:15100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I found the Vite's version is `2.0.0-beta.46`, I try to update the version into `2.0.0-beta.64`, now, the error has been resolved.

## The Second Error

The error has not been resolved, I haven't found a solution yet, need your help!

When I use `yarn build`, the program reports an error:

```
E:\Project\test\demo\vitesse-demo (main -> origin)
λ yarn build
yarn run v1.22.10
$ cross-env NODE_ENV=production vite-ssg build

[vite-ssg] Build for client...
building for production...
✓ 67 modules transformed.
dist/index.html                    1.05kb
dist/manifest.webmanifest          0.28kb
dist/registerSW.js                 0.13kb
dist/ssr-manifest.json             2.43kb
dist/assets/README.27f530f0.js     1.13kb / brotli: 0.40kb
dist/assets/about.a824c120.js      1.56kb / brotli: 0.56kb
dist/assets/[...all].ceba0a27.js   0.22kb / brotli: 0.16kb
dist/assets/[name].708befc2.js     1.38kb / brotli: 0.71kb
dist/assets/app.141bf8a6.css       18.25kb / brotli: 3.86kb
dist/assets/app.09174be0.js        52.93kb / brotli: 15.30kb
dist/assets/vendor.10d959a6.js     77.67kb / brotli: 26.96kb

[vite-ssg] Build for server...
building SSR bundle for production...
✓ 25 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.28kb
.vite-ssg-temp/registerSW.js               0.13kb
.vite-ssg-temp/app.js                      54.40kb
.vite-ssg-temp/assets/style.ecfa198b.css   29.10kb
Error: Cannot find module 'vite-plugin-pages/client'
Require stack:
- E:\Project\test\demo\vitesse-demo\.vite-ssg-temp\app.js
- E:\Project\test\demo\vitesse-demo\node_modules\vite-ssg\dist\node\cli.js
- E:\Project\test\demo\vitesse-demo\node_modules\vite-ssg\bin\vite-ssg.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Module.<anonymous> (E:\Project\test\demo\vitesse-demo\.vite-ssg-temp\app.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Project\\test\\demo\\vitesse-demo\\.vite-ssg-temp\\app.js',
    'E:\\Project\\test\\demo\\vitesse-demo\\node_modules\\vite-ssg\\dist\\node\\cli.js',
    'E:\\Project\\test\\demo\\vitesse-demo\\node_modules\\vite-ssg\\bin\\vite-ssg.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I was using your package [vite-ssg](https://github.com/antfu/vite-ssg) yesterday, but I ran into the same problem.

Please help me see how to solve it when you are free, Thank you!

**Comment by antfu** [comment]
Yeah, that's why I am locking the version for now. There is some bug in the latest version of Vite, but I didn't get time to report it atm. Maybe you can create an issue there.

**Comment by chengpeiquan** [comment]
Thx! Now the problem has been solved!

Just now, I downgrade the Vite to `2.0.0-beta.46`，and reinstall this three package `@vue/server-renderer`, `@vue/compiler-sfc`, `vue-router@next`, now, the project can be successfully constructed!

**Comment by skyrpex** [comment]
https://github.com/hannoeru/vite-plugin-pages renamed the routes file to `import routes from "pages-generated";`

I think it works for me using latest versions of vite and vite-plugin-pages.

**Comment by chengpeiquan** [comment]
> https://github.com/hannoeru/vite-plugin-pages renamed the routes file to `import routes from "pages-generated";`
> 
> I think it works for me using latest versions of vite and vite-plugin-pages.

Thx! So pleasantly surprised! The `vite` and the `vite-plugin-pages` updated the new version at the same time yesterday!

Now I use these latest versions, my project is working!

package|version
:--|:--
vite|2.0.0-beta.65
vite-plugin-pages|0.2.2
